# Generated by Django 5.0.3 on 2024-09-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('health_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('aadhar_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('chronic_conditions', models.TextField()),
                ('profile', models.ImageField(upload_to='profiles/')),
                ('report', models.FileField(upload_to='reports/')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
