# Generated by Django 5.0.3 on 2024-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_no',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
