# Generated by Django 5.0.3 on 2024-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
