# Generated by Django 5.0.3 on 2024-09-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_userprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
