# Generated by Django 5.0.3 on 2024-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_userprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=12)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('tests_ordered', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
